### ISSUE TITLE
Crash when a network share temporarily is unavailable when using v0.7.0

### ISSUE THREAD

**Issue by JordanJones** [RolandPheasant/TailBlazer#108]
I frequently find myself tailing log files from a VM that I access via a UNC path. Occasionally when I restart or shutdown the VM, TailBlazer will crash. Here is the relevant section of the log file:

```csharp
2016-04-21 12:46:31,768 ERROR 7 UhandledExceptionHandler The network path was not found.

System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at TailBlazer.Domain.FileHandling.IndexCollection.<ReadLinesByIndex>d__25.MoveNext() in C:\projects\tailblazer\Source\TailBlazer.Domain\FileHandling\IndexCollection.cs:line 78
   at TailBlazer.Domain.FileHandling.IndexCollection.<ReadLines>d__24.MoveNext() in C:\projects\tailblazer\Source\TailBlazer.Domain\FileHandling\IndexCollection.cs:line 63
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TailBlazer.Domain.FileHandling.LineScroller.<>c.<.ctor>b__5_3(<>f__AnonymousType2`2 x) in C:\projects\tailblazer\Source\TailBlazer.Domain\FileHandling\LineScroller.cs:line 78
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Sample`1._.Tick()
   at System.Reactive.Concurrency.Scheduler.<SchedulePeriodic>b__3(Action a)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<SchedulePeriodic>b__7()
   at System.Reactive.Concurrency.AsyncLock.Wait(Action action)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<SchedulePeriodic>b__6()
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.Tick(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by RolandPheasant** [comment]
Which version are you using?

**Comment by JordanJones** [comment]
Doh.. sorry about that. I updated the title of the issue with the version (0.7.0)

**Comment by mreichardt95** [comment]
I was not able to reproduce the error. 
I tried it over a connected network drive, with a UNC path and a local file. It just closes the text, but no crash

**Comment by RolandPheasant** [comment]
I've have not reproduced the error but the stack tells me the offending code is this:

```
 var aggregator = latest
	.CombineLatest(scrollRequest, (currentLines, scroll) => new { currentLines, scroll})
	.Sample(TimeSpan.FromMilliseconds(50))
	.Select(x =>
	{
	    if (x.scroll== ScrollRequest.None ||  x.scroll.PageSize == 0 || x.currentLines.Count == 0)
		return new Line[0];

	    return x.currentLines.ReadLines(x.scroll).ToArray();
	})
	.Subscribe(currentPage =>
	{
	    var previous = lines.Items.ToArray();
	    var added = currentPage.Except(previous, Line.TextStartComparer).ToArray();
	    var removed = previous.Except(currentPage, Line.TextStartComparer).ToArray();


	    lines.Edit(innerCache =>
	    {
		if (removed.Any()) innerCache.Remove(removed);
		if (added.Any()) innerCache.AddOrUpdate(added);
	    });
	});
```

The offendling line is 
```
return x.currentLines.ReadLines(x.scroll).ToArray();
```
which is causing the error. I will add some code to handle it soon.
