### ISSUE TITLE
TailBlazer 0.7 crashes at start-up

### ISSUE THREAD

**Issue by thoemmi** [RolandPheasant/TailBlazer#85]
TailBlazer crashes on my machine, both the released version 0.7 and the current source code. The exception is thrown in the Dragablz library, bu I don't know if the issue is in that library or in TailBlazer, so I'm reporting it here.

Anyway, here's the stacktrace from the log file:
```
2016-02-27 14:07:00,198 ERROR 1 UhandledExceptionHandler Provide value on 'System.Windows.Markup.StaticExtension' threw an exception.
System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Markup.StaticExtension' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Dragablz.DragablzColors' threw an exception. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: percentage
   at Dragablz.DragablzColors.BlendColor(Color color1, Color color2, Double percentage) in C:\projects\dragablz\Dragablz\DragablzColors.cs:line 60
   at Dragablz.DragablzColors.GetBalancedWindowGlassBrush() in C:\projects\dragablz\Dragablz\DragablzColors.cs:line 36
   at Dragablz.DragablzColors..cctor() in C:\projects\dragablz\Dragablz\DragablzColors.cs:line 20
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.RuntimeFieldHandle.GetValue(RtFieldInfo field, Object instance, RuntimeType fieldType, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.UnsafeGetValue(Object obj)
   at System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
```
I run Windows 10 with the latest Insider build 14271.

**Comment by thoemmi** [comment]
I cloned Dragablz and could reproduce the issue in its sample app. So everything's fine with TailBlazer :wink: I'll open a new issue in the Dragablz repository.

**Comment by thoemmi** [comment]
For reference: https://github.com/ButchersBoy/Dragablz/issues/88

**Comment by RolandPheasant** [comment]
I love the issues which close themselves. These are the very best ones.
